spring.datasource.url=${postgresql://przychodnia_db_user:sO1PJc7YSXDi0JpfF9zMbPKvNtWrtffU@dpg-d4ks51ggjchc73acojk0-a/przychodnia_db}
spring.datasource.username=${przychodnia_db_user}
spring.datasource.password=${sO1PJc7YSXDi0JpfF9zMbPKvNtWrtffU}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=false